### ISSUE TITLE
Added in TableView... conflict scrollview with rate pan gesture

### ISSUE THREAD

**Issue by fredjahanmanesh** [zekunyan/TTGEmojiRate#5]
hi, i use it in a tableview cell, do you have any suggestion about handling pan gesture ... how can i handle tableview vertical scrollview and emoji rate pan gesture?

**Comment by zekunyan** [comment]
Use the gesture delegate i think

**Comment by crspybits** [comment]
After struggling with @farshadjahanmanesh's issue for a few hours, I changed my fork of your very nice Cocoapod to use pan gestures. See https://github.com/crspybits/TTGEmojiRate.git
It seems to work just the same, but also works with scroll views-- or in my case a table view. Are you open to a PR to merge this in?

**Comment by zekunyan** [comment]
@crspybits You can open a PR and i will check this ~ :)

**Comment by crspybits** [comment]
@zekunyan I have just opened a PR :).

**Comment by crspybits** [comment]
Many Thanks @zekunyan!!! I hadn't updated the pod spec with a new version... And probably you'll want to make a new tag/release-- 0.3.0 ?

**Comment by zekunyan** [comment]
@crspybits It's done.
